# Generated by Django 3.2.5 on 2021-08-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_active', '-pub_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='daily_rating',
            field=models.IntegerField(default=0, verbose_name='Daily views count'),
        ),
        migrations.AddField(
            model_name='post',
            name='monthly_rating',
            field=models.IntegerField(default=0, verbose_name='Monthly views count'),
        ),
        migrations.AddField(
            model_name='post',
            name='yearly_rating',
            field=models.IntegerField(default=0, verbose_name='Yearly views count'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Total views count'),
        ),
    ]
