# Generated by Django 3.2.5 on 2021-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_journal', '0002_auto_20210818_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Number of likes'),
        ),
    ]
