# Generated by Django 3.2.4 on 2021-07-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_journal', '0003_auto_20210714_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Пост отображается на сайте?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Основной текст'),
        ),
    ]
