# Generated by Django 3.2.5 on 2021-08-24 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_journal', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_number',
            field=models.IntegerField(default=0, verbose_name='Likes number'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Like date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_journal.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(through='online_journal.PostLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
