# Generated by Django 3.2.5 on 2021-09-14 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_journal', '0004_auto_20210825_0027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
    ]
